### ISSUE TITLE
Issue uploading data into EU endpoint

### ISSUE THREAD

**Issue by jordan-tr** [mParticle/mparticle-python-sdk#16]
Hello,

I'm currently having an issue in pushing data to an eu endpoint using the sdk. We have a test account set up in the US where I don't have any issues after having installed via pip and using the backend feed credentials generated there, however now that I've switched over to our EU credentials I'm running into an error.

I've already switch the config.host url to `https://s2s.eu1.mparticle.com/v2/events` however this doesn't seem to help at all.

Error message:

`Exception while calling mParticle: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 10 Mar 2022 14:05:47 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'Kestrel'})`

**Comment by samdozor** [comment]
Hello! I believe you want to set the host to `https://s2s.eu1.mparticle.com/v2` - without `/events` path - can you give that a shot?

**Comment by jordan-tr** [comment]
hey @samdozor thanks for coming back so quickly. That indeed did it! Perhaps it should be added to the documentation that this needs to be done for EU accounts as I was given the previous endpoint suggestion from the mparticle team here and couldn't find anything to help until you solved it.

**Comment by samdozor** [comment]
Great - glad to hear it. And agreed we should add this to the docs and README. I'll make a note to get that taken care of.
